import streamlit as st
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from pptx import Presentation
from pptx.util import Inches, Pt
import altair as alt
import os

# --- PART 1: POWERPOINT GENERATOR LOGIC ---
def create_ppt():
    prs = Presentation()

    # Slide 1: Title
    slide = prs.slides.add_slide(prs.slide_layouts[0])
    slide.shapes.title.text = "🛡️ Brute Force Attack Detector"
    slide.placeholders[1].text = "Cybersecurity ML Project\nCreated by [Your Name]"

    # Slide 2: The Problem
    slide = prs.slides.add_slide(prs.slide_layouts[1])
    slide.shapes.title.text = "The Threat: Brute Force"
    content = slide.placeholders[1]
    content.text = ("• Attackers use automated scripts to guess passwords.\n"
                    "• High-frequency attempts can crash servers.\n"
                    "• Manual log monitoring is impossible at scale.")

    # Slide 3: ML Logic
    slide = prs.slides.add_slide(prs.slide_layouts[1])
    slide.shapes.title.text = "Machine Learning Logic"
    content = slide.placeholders[1]
    content.text = ("• Algorithm: Random Forest Classifier\n"
                    "• Key Features Analysed:\n"
                    "  - Attempt Velocity (Attempts/Min)\n"
                    "  - Failure Ratio (Failures vs Success)\n"
                    "  - Identity Scope (Unique usernames targeted)")

    # Slide 4: System Architecture
    slide = prs.slides.add_slide(prs.slide_layouts[1])
    slide.shapes.title.text = "System Architecture"
    content = slide.placeholders[1]
    content.text = ("• Web Interface: Streamlit\n"
                    "• Data Analysis: Pandas & NumPy\n"
                    "• Intelligence: Scikit-Learn Model")

    filename = "BruteForce_Presentation.pptx"
    prs.save(filename)
    return filename

# --- PART 2: MACHINE LEARNING MODEL ---
@st.cache_resource
def train_basic_model():
    # Features: [attempts_per_minute, failed_success_ratio, unique_usernames]
    X_train = [
        [1, 0.1, 1], [2, 0.2, 1], [50, 0.9, 10], [100, 1.0, 25],
        [1, 0.0, 1], [3, 0.1, 1], [80, 0.85, 15], [120, 0.98, 40]
    ]
    y_train = [0, 0, 1, 1, 0, 0, 1, 1]
    model = RandomForestClassifier(n_estimators=100, random_state=42)
    model.fit(X_train, y_train)
    return model

# --- PART 3: MAIN APP INTERFACE ---
def main():
    st.set_page_config(page_title="Universal Brute Force Detector", layout="wide")
    
    # Generate PPT automatically on run
    ppt_file = create_ppt()

    st.title("🛡️ Universal Brute Force Detector")
    st.markdown("Analyze login logs using AI to identify potential security threats.")

    # Sidebar: Project Materials
    st.sidebar.header("📁 Project Materials")
    with open(ppt_file, "rb") as f:
        st.sidebar.download_button(
            label="📥 Download Presentation (PPTX)",
            data=f,
            file_name=ppt_file,
            mime="application/vnd.openxmlformats-officedocument.presentationml.presentation"
        )
    st.sidebar.info("The presentation above is automatically generated by the app's backend.")

    model = train_basic_model()

    uploaded_file = st.file_uploader("Upload Login Logs (CSV)", type="csv")

    if uploaded_file is not None:
        df = pd.read_csv(uploaded_file, sep=None, engine='python')
        df.columns = df.columns.str.strip() # Clean headers
        
        st.subheader("Raw Data Preview")
        st.dataframe(df.head())

        # --- Dynamic Column Mapping ---
        st.sidebar.divider()
        st.sidebar.header("⚙️ Column Mapping")
        all_cols = df.columns.tolist()

        # Try to guess columns based on typical names
        def_ip = next((c for c in all_cols if "ip" in c.lower() or "source" in c.lower()), all_cols[0])
        def_att = next((c for c in all_cols if "attempt" in c.lower()), all_cols[0])
        def_ratio = next((c for c in all_cols if "ratio" in c.lower()), all_cols[0])
        def_user = next((c for c in all_cols if "user" in c.lower()), all_cols[0])

        target_ip = st.sidebar.selectbox("Identity (IP) Column", all_cols, index=all_cols.index(def_ip))
        col_att = st.sidebar.selectbox("Attempts Column", all_cols, index=all_cols.index(def_att))
        col_ratio = st.sidebar.selectbox("Failure Ratio Column", all_cols, index=all_cols.index(def_ratio))
        col_user = st.sidebar.selectbox("Unique User Column", all_cols, index=all_cols.index(def_user))

        if st.button("🚀 Run Security Analysis"):
            try:
                # Prepare data for model
                X = pd.DataFrame({
                    'att': pd.to_numeric(df[col_att], errors='coerce').fillna(0),
                    'rat': pd.to_numeric(df[col_ratio], errors='coerce').fillna(0),
                    'usr': pd.to_numeric(df[col_user], errors='coerce').fillna(0)
                })

                predictions = model.predict(X.values)
                df['is_brute_force'] = predictions

                results = df[df['is_brute_force'] == 1]

                if not results.empty:
                    st.error(f"🚨 ALERT: Detected {len(results)} potential Brute Force attempts!")
                    st.table(results[[target_ip, col_att, col_ratio]])
                    
                    # Visualization
                    st.subheader("📊 Attack Distribution")
                    chart = alt.Chart(df).mark_circle(size=100).encode(
                        x=alt.X(col_att, title='Attempts per Minute'),
                        y=alt.Y(col_ratio, title='Failure Ratio'),
                        color=alt.Color('is_brute_force:N', scale=alt.Scale(range=['#2ecc71', '#e74c3c']), title="Threat Status"),
                        tooltip=[target_ip, col_att, col_ratio]
                    ).interactive()
                    st.altair_chart(chart, use_container_width=True)
                else:
                    st.success("✅ Analysis Complete: No brute-force patterns detected.")

            except Exception as e:
                st.error(f"Processing Error: {e}")

if __name__ == "__main__":
    main()